### ISSUE TITLE
Property dot syntax not working following expression

### ISSUE THREAD

**Issue by rweads0520** [mindsung/json-fx#1]
Example:
`$:find($.title == "Things Fall Apart").author`
Should return the author property of the item returned by `:find`. Currently the entire item is return, as if the author property identifier, and after it, are ignored.

**Comment by aceads0529** [comment]
That's a side-effect of not treating the dot operator as a standard
operator. It only gets parsed when part of a regular property path

**Comment by rweads0520** [comment]
Will be fixed by [](https://github.com/mindsung/json-fx/issues/2)
